version: '2'
services:
  users:
    image: anapsix/alpine-java
    #ports:
    #- "91:9000"
    volumes:
    - ./users/target/users.jar:/home/users.jar
    command: ["java","-jar","/home/users.jar"]
    depends_on:
    - mongo
    - songs
  songs:
    image: anapsix/alpine-java
    #ports:
    #- "92:9000"
    volumes:
    - ./songs/target/songs.jar:/home/songs.jar
    command: ["java","-jar","/home/songs.jar"]
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017"
    #volumes:
    #- ./mongo_data:/data/db
  nginx:
    image: nginx
    ports:
    - "80:80"
    depends_on:
    - users
    - songs
    - front-end
    volumes:
    - ./front-end/nginx.conf:/etc/nginx/nginx.conf
    - ./front-end/webapp:/usr/share/nginx/html
    #command: bash -c "sudo chmod -R 0755 /usr/share/nginx/html/*"
  front-end:
    image: tomcat:8.0
    #ports:
    #- "80:8080"
    depends_on:
    - users
    - songs
    volumes:
    - ./front-end/target/front-end.war:/usr/local/tomcat/webapps/songs.war